#!/usr/bin/env bash
# Freeze pinned requirements for reproducible Local v1 installs.
# Lock is optional for day-to-day development; use for release verification.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

LOCK_FILE="${ROOT}/requirements/lock-local-v1.txt"
CHECK_MODE=false

for arg in "$@"; do
  case "${arg}" in
    --check)
      CHECK_MODE=true
      ;;
  esac
done

filter_lock_lines() {
  while IFS= read -r line; do
    case "${line}" in
      -e*)
        continue
        ;;
      sourcelab-ai@file://*|sourcelab-ai@/*|sourcelab-ai==*)
        continue
        ;;
      \#*Editable\ install*sourcelab-ai*)
        continue
        ;;
      \#*)
        continue
        ;;
      "")
        continue
        ;;
      *)
        printf '%s\n' "${line}"
        ;;
    esac
  done
}

generate_lock_content() {
  python -m pip install --upgrade pip setuptools wheel >/dev/null
  python -m pip install -e ".[dev,api,ui,ingest,retrieval,models]" >/dev/null
  python -m pip freeze | filter_lock_lines | LC_ALL=C sort
}

if [[ "${CHECK_MODE}" == "true" ]]; then
  if [[ ! -f "${LOCK_FILE}" ]]; then
    echo "Lock file missing: ${LOCK_FILE}" >&2
    echo "Run: make freeze" >&2
    exit 1
  fi

  TEMP_LOCK="$(mktemp)"
  trap 'rm -f "${TEMP_LOCK}"' EXIT
  generate_lock_content > "${TEMP_LOCK}"

  EXISTING="$(filter_lock_lines < "${LOCK_FILE}" | LC_ALL=C sort)"
  GENERATED="$(cat "${TEMP_LOCK}")"

  if [[ "${EXISTING}" != "${GENERATED}" ]]; then
    echo "Lock file drift detected: ${LOCK_FILE}" >&2
    echo "Run: make freeze" >&2
    exit 1
  fi

  echo "Lock file matches generated requirements."
  exit 0
fi

PYTHON_VERSION="$(python --version 2>&1 | awk '{print $2}')"
GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

python -m pip install --upgrade pip setuptools wheel
python -m pip install -e ".[dev,api,ui,ingest,retrieval,models]"

{
  echo "# SourceLab Local v1 pinned requirements"
  echo "# Python version: ${PYTHON_VERSION}"
  echo "# Generated by scripts/freeze_requirements.sh on ${GENERATED_AT}"
  echo "# Install: pip install -r requirements/lock-local-v1.txt && pip install -e ."
  echo ""
  python -m pip freeze | filter_lock_lines
} > "${LOCK_FILE}"

echo "Wrote ${LOCK_FILE}"
